[project]
name = "jupyter_turtle"
version = "0.0.2"
dependencies = [
    'ipycanvas',
    'face_recognition',
    'importlib-metadata; python_version<"3.8"',
]

[tool.setuptools.packages.find]
where = ["jupyter_turtle"]

[tool.setuptools.package-data]
mypkg = ["*.png"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
